import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import UserGuest from './UserGuest'
import UserList from './UserList'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [session,setSession] = useState(false);
  return (
    <>
      <div>
        <Head>
          <title>Vayuz Task 2</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
         {session ? UserList() : UserGuest() }
      </div>
    </>
  )
}
